<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/feature_construction_and_splitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [8]:
df = pd.read_csv('/content/Titanic-Dataset.csv', usecols = {1,2, 5,6,7})
df

     Survived  Pclass   Age  SibSp  Parch
0           0       3  22.0      1      0
1           1       1  38.0      1      0
2           1       3  26.0      0      0
3           1       1  35.0      1      0
4           0       3  35.0      0      0
..        ...     ...   ...    ...    ...
886         0       2  27.0      0      0
887         1       1  19.0      0      0
888         0       3   NaN      1      2
889         1       1  26.0      0      0
890         0       3  32.0      0      0

[891 rows x 5 columns]

In [9]:
df.dropna(inplace=True)

In [10]:
df

     Survived  Pclass   Age  SibSp  Parch
0           0       3  22.0      1      0
1           1       1  38.0      1      0
2           1       3  26.0      0      0
3           1       1  35.0      1      0
4           0       3  35.0      0      0
..        ...     ...   ...    ...    ...
885         0       3  39.0      0      5
886         0       2  27.0      0      0
887         1       1  19.0      0      0
889         1       1  26.0      0      0
890         0       3  32.0      0      0

[714 rows x 5 columns]

In [11]:
x= df.iloc[:,1:5]
y= df.iloc[:,-5]

In [16]:
x.head()

   Pclass   Age  SibSp  Parch
0       3  22.0      1      0
1       1  38.0      1      0
2       3  26.0      0      0
3       1  35.0      1      0
4       3  35.0      0      0

In [13]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [17]:
np.mean(cross_val_score(LogisticRegression(), x, y, scoring='accuracy', cv=20))

np.float64(0.6933333333333332)

In [18]:
# Applying Feature Contruction
x['Family'] = x['SibSp']+x['Parch']+1

In [19]:
x.head()

   Pclass   Age  SibSp  Parch  Family
0       3  22.0      1      0       2
1       1  38.0      1      0       2
2       3  26.0      0      0       1
3       1  35.0      1      0       2
4       3  35.0      0      0       1

In [21]:
def myfunc(num):
  if num==1:
    #alone
    return 0

  elif num >1 and num<=4:
    #small family
    return 1

  else:
    return 2

In [22]:
x['Family_type']= x['Family'].apply(myfunc)

In [24]:
x.head()

   Pclass   Age  SibSp  Parch  Family  Family_type
0       3  22.0      1      0       2            1
1       1  38.0      1      0       2            1
2       3  26.0      0      0       1            0
3       1  35.0      1      0       2            1
4       3  35.0      0      0       1            0

In [25]:
x.drop(columns = ['SibSp','Parch','Family'],inplace = True)

In [27]:
x.head()

   Pclass   Age  Family_type
0       3  22.0            1
1       1  38.0            1
2       3  26.0            0
3       1  35.0            1
4       3  35.0            0

In [29]:
np.mean(cross_val_score(LogisticRegression(), x, y, scoring='accuracy', cv=20))

np.float64(0.7003174603174602)

In [30]:
# Feature splitting
df = pd.read_csv('/content/Titanic-Dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [31]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [34]:
df['Title'] = df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]
df[['Title','Name']]

    Title                                               Name
0      Mr                            Braund, Mr. Owen Harris
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss                             Heikkinen, Miss. Laina
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr                           Allen, Mr. William Henry
..    ...                                                ...
886   Rev                              Montvila, Rev. Juozas
887  Miss                       Graham, Miss. Margaret Edith
888  Miss           Johnston, Miss. Catherine Helen "Carrie"
889    Mr                              Behr, Mr. Karl Howell
890    Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]