<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/ML_prediction_withpipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# In the dataset i have worked on the accuracy score and prediction of a random input data with PIPELINE
# I have also implemented Cross Validation and Feature scaling in this.
# Even without feature scaling the accuracy score mostly remains same
# I used MinMax because i am doing feature selection also for the specific feature selection i used for that reason i used MinMax
# If i would have not used Feature scaling then i could have used StandardScaler

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.feature_selection import SelectKBest, chi2

In [ ]:
df = pd.read_csv('/content/Titanic-Dataset.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
#df.drop(['PassengerId','Name','Ticket','Cabin'],axis=1)
#df.drop(['PassengerId','Name','Ticket','Cabin'],axis=1, inplace = True)
#df.drop(columns= ['PassengerId','Name','Ticket','Cabin'],inplace =True)
df.drop(columns= ['PassengerId','Name','Ticket','Cabin'],axis=1,inplace =True)

In [ ]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns =['Survived'],axis=1 ),df['Survived'],test_size = 0.2, random_state=42)

In [ ]:
x_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [ ]:
#for missing values

In [ ]:
# using transformer
#imputation
trf1 = ColumnTransformer([
    ('impute_age',SimpleImputer(),[2]),
    ('impute_emb',SimpleImputer(strategy='most_frequent'),[6])
],remainder = 'passthrough')

In [ ]:
#ohe
trf2 = ColumnTransformer([
    ('ohe_sex_emb',OneHotEncoder(sparse_output = False,handle_unknown = 'ignore'),[1,6])
],remainder = 'passthrough')

In [ ]:
#scaling
trf3 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
])

In [ ]:
#feature selection
trf4 = SelectKBest(score_func=chi2,k=8)

In [ ]:
#DTC
trf5 = DecisionTreeClassifier()

In [ ]:
# MAKING A PIPELINE

#pipe = Pipeline([
#    ('trf1',trf1),
#    ('trf2',trf2),
#    ('trf3',trf3),
#    ('trf4',trf4),
#    ('trf5',trf5)
#])

# pipeline vs make_pipeline
# same goes for ColumnTransformer vs make_column_transformer

#alternative syntax
pipe = make_pipeline(trf1,trf2,trf3,trf4,trf5)

In [ ]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_emb',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_emb',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('columntransformer-3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x7f67b7e02c00>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [ ]:
# prediction
y_pred = pipe.predict(x_test)
y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test,y_pred)

0.6256983240223464

Cross validation using pipeline

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cross_val_score(pipe,x_train,y_train,cv =5, scoring='accuracy').mean()

np.float64(0.6391214419383433)

In [ ]:
# exporting the pipeline
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

In [ ]:
import pickle
import numpy as np

In [ ]:
pipe = pickle.load(open('pipe.pkl','rb'))

In [ ]:
# assumed user input
test_input=np.array([2,'male',31.0,0,0,10.5,'S'],dtype = object).reshape(1,7)

In [ ]:
pipe.predict(test_input)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(

array([0])